version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: ${LOCAL_DB}
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_PASSWORD}
      MYSQL_DATABASE: ${LOCAL_DB}
      MYSQL_USER: ${LOCAL_USER}
      MYSQL_PASSWORD: ${LOCAL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
